"""Guard against hard-coded, stale pytest counts in paper-facing documents.

The exact number of tests in the suite changes whenever a test is added, so the
paper and headline docs must not bake a specific count (e.g. "382 tests" or
"382/382 pass") into a test-suite pass claim. Stable wording such as "the full
test suite passes" should be used instead, with the current count recorded in the
reproducibility logs / final audit output.

This test only inspects the paper-facing documents. ``results/final_report/`` is a
generated result artifact and is intentionally excluded (it is regenerated by the
final-report pipeline, not hand-edited).
"""

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

PAPER_FACING_FILES = [
    "README.md",
    "FINAL_ARTIFACT_INDEX.md",
    "FINAL_RESULTS_CHECKLIST.md",
    "paper/main.tex",
    "paper/tables/tables.md",
]

# Forms that bind an explicit number to a test-suite pass claim. The patterns stay
# scoped to the test-suite clause (``[^.\n]`` never crosses a sentence or line
# boundary) so they do not trip on experimental metrics, the fixed negative-control
# count, or model-loading counts that legitimately share the same paragraph.
_STALE_PYTEST_COUNT_PATTERNS = [
    re.compile(r"test suite passes[^.\n]*?\d", re.IGNORECASE),
    re.compile(r"test suite[^.\n]*?[:|]\s*\d", re.IGNORECASE),
]


def test_paper_facing_files_do_not_hardcode_pytest_counts():
    offenders = []
    for rel in PAPER_FACING_FILES:
        text = (REPO / rel).read_text(encoding="utf-8")
        for pattern in _STALE_PYTEST_COUNT_PATTERNS:
            for match in pattern.finditer(text):
                snippet = match.group(0).replace("\n", " ").strip()
                offenders.append(f"{rel}: {snippet!r}")

    assert not offenders, (
        "Paper-facing files must not hard-code an exact pytest count (it goes "
        "stale whenever tests are added). Use stable wording such as 'the full "
        "test suite passes' and record the current count in the reproducibility "
        "logs / final audit output. Offenders:\n  " + "\n  ".join(offenders)
    )
