"""Generate small, synthetic, non-sensitive demo images.

These are illustrative inputs for the CIC demo flow. They are generated (not
copied from any dataset) so the demo ships no raw COCO / train2014 / large
assets. Re-run with ``python3 demo/sample_images/generate_samples.py``.

The four examples mirror scenarios discussed in the project:
  * controlled text-overlay success  -> object + big distracting word
  * semantic-decoy success           -> object + a decoy object word
  * COCO-Text directional example    -> a scene-text band over an object
  * failure / abstain example        -> ambiguous, low-signal image
"""

from __future__ import annotations

import json
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


HERE = Path(__file__).resolve().parent


def _font(size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    for candidate in (
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
        "/System/Library/Fonts/Helvetica.ttc",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    ):
        if Path(candidate).exists():
            try:
                return ImageFont.truetype(candidate, size)
            except OSError:
                continue
    return ImageFont.load_default()


def _base(color: tuple[int, int, int], size: int = 256) -> Image.Image:
    img = Image.new("RGB", (size, size), color)
    draw = ImageDraw.Draw(img)
    # A simple central "object" blob so proposals have an object vs. text contrast.
    draw.ellipse([size * 0.28, size * 0.30, size * 0.72, size * 0.78],
                 fill=(int(color[0] * 0.55) + 40, int(color[1] * 0.55) + 30, int(color[2] * 0.55) + 20))
    return img


def _text_band(img: Image.Image, text: str, y_frac: float, font_size: int) -> None:
    draw = ImageDraw.Draw(img)
    font = _font(font_size)
    w, h = img.size
    bbox = draw.textbbox((0, 0), text, font=font)
    tw = bbox[2] - bbox[0]
    x = max(4, (w - tw) // 2)
    y = int(h * y_frac)
    pad = 6
    draw.rectangle([x - pad, y - pad, x + tw + pad, y + (bbox[3] - bbox[1]) + pad], fill=(245, 245, 245))
    draw.text((x, y - bbox[1]), text, fill=(15, 15, 15), font=font)


def generate() -> list[dict]:
    specs = [
        {
            "name": "text_overlay_success",
            "scenario": "controlled text-overlay success",
            "color": (60, 120, 200),
            "text": "DOG",
            "y_frac": 0.07,
            "font_size": 30,
            "note": "Distracting word over an object blob. Mock demo: the text-driven "
                    "prediction is repaired to the object after CIC neutralization.",
        },
        {
            "name": "semantic_decoy_success",
            "scenario": "semantic-decoy success",
            "color": (70, 150, 90),
            "text": "LAPTOP",
            "y_frac": 0.82,
            "font_size": 26,
            "note": "Decoy object word competing with the central object. Mock demo: "
                    "prediction is repaired to the object after CIC neutralization.",
        },
        {
            "name": "coco_text_directional",
            "scenario": "COCO-Text directional example",
            "color": (30, 160, 150),
            "text": "STREET SIGN",
            "y_frac": 0.09,
            "font_size": 24,
            "note": "Scene-text band, like directional/street signage over an object. "
                    "Mock demo: a finite-candidate case where neutralization does NOT yield a "
                    "confident repair -- CIC is not guaranteed open-world shortcut discovery.",
        },
        {
            "name": "failure_abstain",
            "scenario": "failure / abstain example",
            "color": (175, 85, 35),
            "text": "STOP AHEAD",
            "y_frac": 0.09,
            "font_size": 24,
            "note": "High-confidence text shortcut over an ambiguous object. Mock demo: "
                    "neutralization is unstable so the reliability gate ABSTAINS instead of trusting it.",
        },
    ]
    manifest = []
    for spec in specs:
        img = _base(spec["color"])
        if spec["text"]:
            _text_band(img, spec["text"], spec["y_frac"], spec["font_size"])
        path = HERE / f"{spec['name']}.png"
        img.save(path)
        manifest.append(
            {
                "name": spec["name"],
                "file": f"{spec['name']}.png",
                "scenario": spec["scenario"],
                "overlay_text": spec["text"],
                "note": spec["note"],
                "synthetic": True,
            }
        )
    with open(HERE / "manifest.json", "w", encoding="utf-8") as handle:
        json.dump(
            {
                "synthetic": True,
                "source": "generated by demo/sample_images/generate_samples.py",
                "disclaimer": "Synthetic illustrative inputs. Not dataset samples, not evidence.",
                "images": manifest,
            },
            handle,
            indent=2,
        )
    return manifest


if __name__ == "__main__":
    items = generate()
    for item in items:
        print(f"wrote {item['file']:32s} - {item['scenario']}")
